### ISSUE TITLE
armv7 build fail

### ISSUE THREAD

**Issue by zeljic** [lasote/conan-zlib#1]
I've tried to build zlib on Raspberry Pi 2
`uname -a`
`Linux ironhills 4.1.17-v7+ #838 SMP Tue Feb 9 13:15:09 GMT 2016 armv7l GNU/Linux`

Here is output https://gist.github.com/zeljic/4b53477c04039452386e
I'm not sure but I think issue is  -mstackrealign argument
When I remove that arg from conanfile.py and manually build from _hash_ dir in .conan it works fine

**Comment by zeljic** [comment]
@lasote thanks for your answer and fix (note on gist)
It works now.
BTW. I've built 4 libs on raspberry pi 2:
OpenSSL/1.0.2e@lasote/stable
Poco/1.6.1@lasote/stable
electric-fence/2.2.0@lasote/stable
zlib/1.2.8@lasote/stable
I didn't try them in project, yet, but building is OK, without errors.

**Comment by lasote** [comment]
Great! I close the issue. If you have any trouble just open another one.
