### ISSUE TITLE
zlib 1.2.8 changed download link

### ISSUE THREAD

**Issue by Phibedy** [lasote/conan-zlib#10]
hi,
I think they changed the 1.2.8 path, 1.2.9 works.
ERROR: zlib/1.2.8@lasote/stable: Error in source() method, line 27
	download("http://zlib.net/zlib128.zip", zip_name)
	Error 404 downloading file http://zlib.net/zlib128.zip

Is it possible to find out easily which package uses zlib 1.2.8? I checked all installed conan packages but couldn't find it. Atm I am overriding it with 1.2.9 in my main conan-file

Cheers
Phibedy

**Comment by lasote** [comment]
Hi @Phibedy 
I updated the zlib recipe some days ago, try doing `conan install` with the `-u` option to update the zlib/1.2.8@lasote/stable recipe or remove it first from local cache with `conan remove zlib/1.2.8@lasote/stable`. Please tell me if it works!

About your second question, if you are in a project you can use the `conan info` command to know about the dependencies but currently we don't have an specific search to know all the packages depending on an specific one. Maybe doing some `grep` and searching for `zlib/1.2.8@lasote/stable` could help.

**Comment by Phibedy** [comment]
@lasote, ah I just used  `conan install <p> --build=outdated`, but that does not update the recipe, thank you :)

**Comment by cinderblocks** [comment]
zlib is now at 1.2.10, so neither http://zlib.net/zlib128.zip nor http://zlib.net/zlib129.zip exist.

**Comment by lasote** [comment]
@cinderblocks 
Conan zlib 1.2.8 and 1.2.9 recipes are not using `http://zlib.net/zlibXXX.zip` urls anymore.
I download the source code using:

```
zip_name = "zlib-%s.tar.gz" % self.version
download("http://downloads.sourceforge.net/project/libpng/zlib/%s/%s" % (self.version, zip_name), zip_name)
```
So if it still fails in you computer use the ``--build=outdated`` or the `-u` option to get the latest recipe.
If someone want collaborate with a Pull Request for 1.2.10 would be great!
