### ISSUE TITLE
CMake dependency

### ISSUE THREAD

**Issue by tim-lebedkov** [lasote/conan-zlib#17]
CMake is not automatically installed.

**Comment by lasote** [comment]
Conan nor the recipe mean to install the build tools.
If you want, conan support [``build_requires``](http://docs.conan.io/en/latest/mastering/build_requires.html), It allows you to create conan packages for your build tools, in this case CMake, you could use ``cmake_installer/0.1@lasote/stable`` as a build require specified in a profile, the environment variables and cpp_info flags will be automatically injected in your real dependency tree, so your dependencies will find CMake.

So, create a profile file, include ``cmake_installer/0.1@lasote/stable`` in the ``[build_requires]`` section, optionally add different default settings, like your compiler, compiler version, etc.

Then you can call ``conan install`` command specifing the profile:

```
conan install --profile path/to/yourprofile
```
