### ISSUE TITLE
Fails to build using MinGW

### ISSUE THREAD

**Issue by tarred** [lasote/conan-zlib#2]
While attempting to test a fix to build [conan-openssl with MinGW](https://github.com/lasote/conan-openssl/issues/6) for the Getting Started project I noticed that this dependency also fails to build with MinGW.

The first command to cmake succeeds `cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCONAN_COMPILER="gcc" -DCONAN_COMPILER_VERSION="4.9" -Wno-dev`

But the cmake build command fails:
`zlib/1.2.8@lasote/stable: WARN: cd _build && cmake --build .
[  2%] Generating zlib1rc.obj
Scanning dependencies of target zlib
[  4%] Building C object zlib-1.2.8/CMakeFiles/zlib.dir/adler32.obj
[  7%] Building C object zlib-1.2.8/CMakeFiles/zlib.dir/compress.obj
[  9%] Building C object zlib-1.2.8/CMakeFiles/zlib.dir/crc32.obj
[ 12%] Building C object zlib-1.2.8/CMakeFiles/zlib.dir/deflate.obj
[ 14%] Building C object zlib-1.2.8/CMakeFiles/zlib.dir/gzclose.obj
[ 17%] Building C object zlib-1.2.8/CMakeFiles/zlib.dir/gzlib.obj
[ 19%] Building C object zlib-1.2.8/CMakeFiles/zlib.dir/gzread.obj
[ 21%] Building C object zlib-1.2.8/CMakeFiles/zlib.dir/gzwrite.obj
[ 24%] Building C object zlib-1.2.8/CMakeFiles/zlib.dir/inflate.obj
[ 26%] Building C object zlib-1.2.8/CMakeFiles/zlib.dir/infback.obj
[ 29%] Building C object zlib-1.2.8/CMakeFiles/zlib.dir/inftrees.obj
[ 31%] Building C object zlib-1.2.8/CMakeFiles/zlib.dir/inffast.obj
[ 34%] Building C object zlib-1.2.8/CMakeFiles/zlib.dir/trees.obj
[ 36%] Building C object zlib-1.2.8/CMakeFiles/zlib.dir/uncompr.obj
[ 39%] Building C object zlib-1.2.8/CMakeFiles/zlib.dir/zutil.obj
[ 41%] Linking C shared library ..\bin\libzlib.dll
[ 41%] Built target zlib
Scanning dependencies of target minigzip64
[ 43%] Building C object zlib-1.2.8/CMakeFiles/minigzip64.dir/test/minigzip.obj
C:\Users\x\.conan\data\zlib\1.2.8\lasote\stable\build\fc1fe9866875f4dc8a987ee6dfc0f620a6a2905f\zlib-1.2.8\test\minigzip.c:18:18: fatal error: zlib.h: No such file or directory
 #include "zlib.h"
                  ^
compilation terminated.`

Copying the zlib.h header to the fc1f...\zlib-1.2.8\test directory allows the build to complete (minigzip is just a test/example use of the library) but seems like a sloppy solution, could zlib's cmake test targets be excluded somehow?

**Comment by lasote** [comment]
I don't know...It's the main problem with the libraries, conan works well, but only if the libraries build system/scripts works well. If library build script for mingw is broken... conan already can patch some sources or offer an alternative script but it's a hard work. 

I searched a little and it seems that the mingw support is using the Makefile, something like:

```
C:\MinGW\bin\mingw32-make.exe -fwin32/Makefile.gcc
```

But its needed to know how to pass to the makefile all the configuration (build type, arch...).
I would like to help you with this but I'm toooo busy these days... please write me if you make any progress or have any doubt.

**Comment by tarred** [comment]
I spent some more time looking into this issue and it looks like the root cause is that zlib doesn't lend itself to being added as a subdirectory to another cmake project (this one.) The supplied cmake commands work when building zlib's cmake project by itself, but not the project you add zlib as a subdirectory to.

Replacing CMAKE_SOURCE_DIR with CMAKE_CURRENT_SOURCE_DIR in the includes in zlib's CMakeLists fixes this issue and propagates the right includes into the depend.make file for the minigzip target's CMakeFiles.

I don't have much experience with this build system so I am not sure how to fix this without bypassing the setup in conanbuildinfo.cmake, but if you can provide advice/direction for how to tackle this problem I'd be willing to take a crack at it.
