### ISSUE TITLE
Error while initializing requirements. update() takes exactly 5 arguments (1 given)

### ISSUE THREAD

**Issue by lovelace** [lasote/conan-zlib#21]
Using conan 0.26.1 on OpenSuSE 11.4 when running conan create I get the following output:
```
> conan create ka/testing
zlib/1.2.8@ka/testing: Exporting package recipe
zlib/1.2.8@ka/testing: A new conanfile.py version was exported
zlib/1.2.8@ka/testing: Folder: /home/build/.conan/data/zlib/1.2.8/ka/testing/export
ERROR: Error while initializing requirements. update() takes exactly 5 arguments (1 given)
```

**Comment by lovelace** [comment]
Python version is 2.7

**Comment by lovelace** [comment]
Actually, it looks like this happens with any recipe. This was just the first one I tried.

**Comment by lasote** [comment]
I can't reproduce the error. And it's very strange that it happens with more than one recipe. Could it be something wrong in your configuration folder? Try (if possible) to remove or rename the `~/.conan` folder and try again.

**Comment by lasote** [comment]
I've faced the same issue with an old python 2.7 version. Please upgrade to 2.7.11 or higher.
