### ISSUE TITLE
MinGW-w64 builds

### ISSUE THREAD

**Issue by tim-lebedkov** [lasote/conan-zlib#4]
I created a MinGW build by copying your packages and building it with MinGW-w64/i686. Would you accept the necessary changes to this project? What should I do to make this happen?

**Comment by lasote** [comment]
Of course, if you have changes in the conanfile.py just make a Pull Request.
About auto-generate the MinGW packages could require some time to prepare the conan_package_tools to automatic create these packages. But I can try it!

Thanks!

**Comment by tim-lebedkov** [comment]
I think, I found a bug in "conan-package-tools". Here is the output of "conan-zlib" with my modifications to support gcc: 

`DEBUG: - Skipped build, compiler mismatch: {'compiler.version': '4.8', 'arch': 'x86', 'build_type': 'Debug', 'compiler': 'gcc'}`

The error seems to be produced by "conan-package-tools/conan/packager.py" in "ConanMultiPackager._execute_test":

Here is the code:

```
        if settings.get("compiler") != "Visual Studio":  # Pending until issue #186 is done
            if settings.get("compiler", None) and settings.get("compiler.version", None):
                conan_compiler, conan_compiler_version = self.conan_compiler_info()
                if conan_compiler != settings.get("compiler") or \
                   conan_compiler_version != settings.get("compiler.version"):
                    self.logger.debug("- Skipped build, compiler mismatch: %s" % str(dict(settings)))
                    return  # Skip this build, it's not for this machine

```

I am not sure why these checks are done.

**Comment by lasote** [comment]
Hi,
Conan package tools generate few combinations of settings for several compilers, gcc 4.8, 4.9 etc, but just the combination that matches with your current installed compiler will be executed.

Don't care too much about conan_package_tools, If you want to test if zlib is building ok just use:

```
conan export lasote/testing
conan test_package
```

This way will compile the zlib package with your current settings (Compiler etc) and then compiles an example that links with the zlib package.

**Comment by tim-lebedkov** [comment]
I started another branch without "conan_package_tools": https://github.com/tim-lebedkov/conan-zlib/tree/mingw_without_conan_package_tools

But now there is a compilation error "zlib.h: No such file or directory": https://ci.appveyor.com/project/tim-lebedkov/conan-zlib/build/1.0.15/job/otc2wi41ei73o0v5#L165

Could you please take a look? I have never used "CMake" before and it would take me probably 2 or 3 days to fix this. Maybe you can find a solution quickly. If not, do you know hot to enable debug output in "conan.exe" and "CMake"?

**Comment by tim-lebedkov** [comment]
I fixed the problem with "zlib.h". Now 32 and 64 bit builds are OK. The two remaining problems are:
- "Debug" builds do not work because "zlib" libraries are generated, but "zlibd" are expected. Is this a bug with the GCC support?
- the compiler I use is not simply "GCC 4.9", it's "GCC 4.9 with SEH exception handling and Posix threads". Does "Conans" support this already?

**Comment by tim-lebedkov** [comment]
it works now so I'd close this issue.
