### ISSUE TITLE
zlib 1.2.8 source download link broken

### ISSUE THREAD

**Issue by bjd** [lasote/conan-zlib#8]
Probably because of 1.2.9 release yesterday. 

> zlib/1.2.8@lasote/stable: Installing package 82b1dd29b2e9143665c77ef477100c690d719cbf
> zlib/1.2.8@lasote/stable: WARN: Forced build from source
> zlib/1.2.8@lasote/stable: Building your package in /home/bjd/.conan/data/zlib/1.2.8/lasote/stable/build/82b1dd29b2e9143665c77ef477100c690d719cbf
> zlib/1.2.8@lasote/stable: Configuring sources in /home/bjd/.conan/data/zlib/1.2.8/lasote/stable/source
> zlib/1.2.8@lasote/stable: WARN: Trying to remove dirty source folder
> zlib/1.2.8@lasote/stable: WARN: This can take a while for big packages
ERROR: zlib/1.2.8@lasote/stable: Error in source() method, line 27
	download("http://zlib.net/zlib128.zip", zip_name)
	Error 404 downloading file http://zlib.net/zlib128.zip

**Comment by lasote** [comment]
@bjd Thanks!!! I've fixed the url and prepared the zlib 1.2.9 package too. Both will be available in few minutes.

**Comment by bjd** [comment]
Thanks, it works
